#!/bin/bash

function chk_prog() {
  make -s $1
  if [ "$?" != "0" ]
  then
    echo ERROR: Could not create program \"$1\".
    exit 1
  fi
}

chk_prog checker

RET_STATUS=0
TEST_NUM=0
function chk_map() {
  TEST_NUM=`expr $TEST_NUM + 1`
  ./checker ../task/maps/$1.map $2 $3 $4
  if [ "$?" == "0" ]
  then
    echo Test $TEST_NUM \($1\): PASSED
  else
    echo Test $TEST_NUM \($1\): FAILED
    RET_STATUS=1
  fi
}

chk_map sample DDDLLLLLLURRRRRRRRRRLLLLLLDDDDDDDDLLLRRRRRRRRDDRRRD WON 399
chk_map rocks_fall1 L LOST -1
chk_map rocks_fall2 L ABORTED -1
chk_map rocks_fall3 W ABORTED -1
chk_map rocks_fall4 D LOST -1
chk_map contest1 LDRDDUULLLDDL WON 212
chk_map contest1 DD LOST -2
chk_map contest1 DLLLDD ABORTED 94
chk_map contest2 RRUDRRULURULLLLDDDL WON 281
chk_map contest2 RRRRUD LOST 19
chk_map contest3 LDDDRRRRDDLLLLLDURRRUURRR WON 275
chk_map contest4 URDDLRDRDRDRRLUUURUULURDR WON 575
chk_map contest5 LLUURUUUUURRRRRDLDRRRDDDDDLLRRUUUUULLLLLLDDDRRDDD WON 1301
chk_map contest6 RUULRRRRRRRRRRUUURRDDDDDLLLLLLLLLRRRRRRRRRRUUUUULUURUUULULLULLLLLLLLLDRDLDDDDRUURRRRRUDLLLLLLDDDDRRRRRRRR WON 1170
chk_map contest7 RDRRRDDLLLDDLLRRURURRRDDRRRLLLULL WON 867
chk_map contest8 UUUUURLLWRUUUUUUULLLLLUUULLLLRRDDDDDDLDURLLDDUURRDDDDLLRRRUUUUUUUUUURRDDDDDDDDDDRRRDDDDLLLLLRRRRRUURRRRRRRRRLUURUUUULLULLLLLDDDDDDDDDDRRRRRLLLLLD WON 1955
chk_map contest9 LURURRRDULLLDDRRRRRRRRRRRRRRRULURRRRRRRRDDDLLLULDUULLLLLRRLLULLLLURRRLLUUUULLLLLLURRUULLLDDLLRUURRRRRUURRRRURRDDDRRRDDRRRURRDDUULLDLLLUULLLUUULLLLLLU WON 3076
chk_map contest10 UUUUULLLLLLLLLLDDLLLLUUULLLLDDLLLLLDRRRRRUUULLLLLLLLUURRRRUUUUULLUULLUURRRLUUURDDRURRRRRUURRRRRRRRRRRRRRRRRDDDDDLLUUULLLLULLLDDDRRUDLLLDDDDDLLDDURRDLDURUURRDDRRRRRUURRDRLULLDDDDLLLDDDDURRDLDDRRRRRDDD WON 3626
chk_map contest10 UUUUUUUUUUULRDD LOST 110

exit "$RET_STATUS"
